import { City } from "./types";

// Mock Cities Data
export const mockCities: City[] = [
  {
    id: "1",
    name: "서울 성수동",
    slug: "seoul-seongsu",
    imageUrl: "/images/seongsu.jpg",
    description: "트렌디한 카페와 창업 문화가 살아있는 핫플레이스",
    likes: 892,
    dislikes: 178,
    budget: "100~200만원",
    region: "수도권",
    environment: ["도시선호", "카페작업"],
    bestSeason: "봄",
    monthlyCost: 1850000,
    rentCost: 650000,
    cafeCost: 5000,
    currentTemp: 12,
    currentWeather: "흐림",
    currentAQI: 42,
    tags: ["트렌디", "카페많음", "창업가"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "2",
    name: "제주 제주시",
    slug: "jeju-city",
    imageUrl: "/images/jeju.jpg",
    description: "자연과 함께하는 여유로운 노마드 라이프",
    likes: 756,
    dislikes: 151,
    budget: "100~200만원",
    region: "제주도",
    environment: ["자연친화", "카페작업"],
    bestSeason: "여름",
    monthlyCost: 1650000,
    rentCost: 550000,
    cafeCost: 4500,
    currentTemp: 18,
    currentWeather: "맑음",
    currentAQI: 15,
    tags: ["힐링", "자연", "여유로움"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: "3",
    name: "부산 해운대",
    slug: "busan-haeundae",
    imageUrl: "/images/haeundae.jpg",
    description: "바다가 보이는 카페에서 일하는 로망",
    likes: 1023,
    dislikes: 205,
    budget: "100~200만원",
    region: "경상도",
    environment: ["도시선호", "카페작업"],
    bestSeason: "가을",
    monthlyCost: 1550000,
    rentCost: 500000,
    cafeCost: 4000,
    currentTemp: 15,
    currentWeather: "구름조금",
    currentAQI: 28,
    tags: ["바다", "온천", "관광"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: "4",
    name: "강릉",
    slug: "gangneung",
    imageUrl: "/images/gangneung.jpg",
    description: "커피의 도시, 바다와 산이 공존하는 곳",
    likes: 423,
    dislikes: 85,
    budget: "100~200만원",
    region: "강원도",
    environment: ["자연친화", "카페작업"],
    bestSeason: "여름",
    monthlyCost: 1350000,
    rentCost: 450000,
    cafeCost: 4000,
    currentTemp: 10,
    currentWeather: "맑음",
    currentAQI: 18,
    tags: ["커피", "바다", "조용함"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "5",
    name: "전주",
    slug: "jeonju",
    imageUrl: "/images/jeonju.jpg",
    description: "한옥마을과 맛집이 있는 문화도시",
    likes: 312,
    dislikes: 62,
    budget: "100~200만원",
    region: "전라도",
    environment: ["도시선호", "카페작업"],
    bestSeason: "봄",
    monthlyCost: 1200000,
    rentCost: 400000,
    cafeCost: 3500,
    currentTemp: 13,
    currentWeather: "흐림",
    currentAQI: 35,
    tags: ["문화", "맛집", "저렴"],
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-10-30"),
  },
  {
    id: "6",
    name: "대전",
    slug: "daejeon",
    imageUrl: "/images/daejeon.jpg",
    description: "과학과 IT가 공존하는 중부권 거점 도시",
    likes: 534,
    dislikes: 107,
    budget: "100~200만원",
    region: "충청도",
    environment: ["도시선호", "코워킹 필수"],
    bestSeason: "가을",
    monthlyCost: 1400000,
    rentCost: 480000,
    cafeCost: 4000,
    currentTemp: 11,
    currentWeather: "맑음",
    currentAQI: 30,
    tags: ["IT", "조용함", "교통편리"],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: "7",
    name: "인천 송도",
    slug: "incheon-songdo",
    imageUrl: "/images/songdo.jpg",
    description: "미래형 스마트 도시에서의 쾌적한 업무 환경",
    likes: 645,
    dislikes: 129,
    budget: "100~200만원",
    region: "수도권",
    environment: ["도시선호", "코워킹 필수"],
    bestSeason: "가을",
    monthlyCost: 1700000,
    rentCost: 600000,
    cafeCost: 4500,
    currentTemp: 11,
    currentWeather: "흐림",
    currentAQI: 38,
    tags: ["스마트시티", "깨끗함", "현대적"],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: "8",
    name: "속초",
    slug: "sokcho",
    imageUrl: "/images/sokcho.jpg",
    description: "동해 바다와 설악산이 어우러진 자연 속 워케이션",
    likes: 389,
    dislikes: 78,
    budget: "100만원 이하",
    region: "강원도",
    environment: ["자연친화", "카페작업"],
    bestSeason: "여름",
    monthlyCost: 950000,
    rentCost: 350000,
    cafeCost: 3500,
    currentTemp: 9,
    currentWeather: "맑음",
    currentAQI: 12,
    tags: ["바다", "자연", "조용함"],
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "9",
    name: "대구",
    slug: "daegu",
    imageUrl: "/images/daegu.jpg",
    description: "생활비가 저렴하고 카페 문화가 발달한 경북 중심지",
    likes: 467,
    dislikes: 93,
    budget: "100만원 이하",
    region: "경상도",
    environment: ["도시선호", "카페작업"],
    bestSeason: "봄",
    monthlyCost: 980000,
    rentCost: 370000,
    cafeCost: 3000,
    currentTemp: 14,
    currentWeather: "맑음",
    currentAQI: 25,
    tags: ["저렴", "카페많음", "맛집"],
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: "10",
    name: "광주",
    slug: "gwangju",
    imageUrl: "/images/gwangju.jpg",
    description: "예술과 문화가 살아있는 전라도의 중심 도시",
    likes: 401,
    dislikes: 80,
    budget: "100만원 이하",
    region: "전라도",
    environment: ["도시선호", "카페작업"],
    bestSeason: "가을",
    monthlyCost: 900000,
    rentCost: 340000,
    cafeCost: 3000,
    currentTemp: 13,
    currentWeather: "구름조금",
    currentAQI: 28,
    tags: ["예술", "문화", "저렴"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-10-31"),
  },
  {
    id: "11",
    name: "서울 강남",
    slug: "seoul-gangnam",
    imageUrl: "/images/gangnam.jpg",
    description: "프리미엄 코워킹과 네트워킹의 중심지",
    likes: 723,
    dislikes: 145,
    budget: "200만원 이상",
    region: "수도권",
    environment: ["도시선호", "코워킹 필수"],
    bestSeason: "봄",
    monthlyCost: 2300000,
    rentCost: 850000,
    cafeCost: 6000,
    currentTemp: 12,
    currentWeather: "흐림",
    currentAQI: 45,
    tags: ["프리미엄", "네트워킹", "편리함"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-11-03"),
  },
];

// Mock Reviews Data
export const mockReviews: Review[] = [
  {
    id: "1",
    cityId: "1",
    userId: "user1",
    userName: "김디지털",
    cityName: "서울 성수동",
    rating: 5.0,
    content: "카페가 정말 많고 분위기도 좋아요. 콘센트 걱정 없고 와이파이도 빠릅니다.",
    tags: ["카페천국", "콘센트많음", "와이파이빠름"],
    createdAt: new Date("2024-11-03T14:30:00"),
    updatedAt: new Date("2024-11-03T14:30:00"),
  },
  {
    id: "2",
    cityId: "2",
    userId: "user2",
    userName: "박노마드",
    cityName: "제주 제주시",
    rating: 4.5,
    content: "자연이 아름답고 여유로운 분위기가 좋아요. 다만 생활비가 생각보다 높네요.",
    tags: ["자연", "힐링", "조용함"],
    createdAt: new Date("2024-11-03T10:15:00"),
    updatedAt: new Date("2024-11-03T10:15:00"),
  },
  {
    id: "3",
    cityId: "3",
    userId: "user3",
    userName: "이프리랜서",
    cityName: "부산 해운대",
    rating: 4.8,
    content: "바다 보면서 일할 수 있는 카페들이 많아요. 날씨도 좋고 사람들도 친절합니다!",
    tags: ["바다뷰", "날씨좋음", "친절"],
    createdAt: new Date("2024-11-02T16:45:00"),
    updatedAt: new Date("2024-11-02T16:45:00"),
  },
];
