import { City, Meetup, Review } from "./types";

// Mock Cities Data
export const mockCities: City[] = [
  {
    id: "1",
    name: "서울 성수동",
    region: "서울/경기",
    slug: "seoul-seongsu",
    imageUrl: "/images/seongsu.jpg",
    description: "트렌디한 카페와 창업 문화가 살아있는 핫플레이스",
    overallRating: 4.8,
    cafeRating: 5.0,
    costRating: 2.5,
    internetRating: 5.0,
    housingRating: 2.8,
    reviewCount: 327,
    likeCount: 892,
    monthlyCost: 1850000,
    rentCost: 650000,
    cafeCost: 5000,
    currentTemp: 12,
    currentWeather: "흐림",
    currentAQI: 42,
    tags: ["트렌디", "카페많음", "창업가"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "2",
    name: "제주 제주시",
    region: "제주",
    slug: "jeju-city",
    imageUrl: "/images/jeju.jpg",
    description: "자연과 함께하는 여유로운 노마드 라이프",
    overallRating: 4.6,
    cafeRating: 4.8,
    costRating: 4.2,
    internetRating: 4.5,
    housingRating: 3.5,
    reviewCount: 289,
    likeCount: 756,
    monthlyCost: 1650000,
    rentCost: 550000,
    cafeCost: 4500,
    currentTemp: 18,
    currentWeather: "맑음",
    currentAQI: 15,
    tags: ["힐링", "자연", "여유로움"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: "3",
    name: "부산 해운대",
    region: "부산/경남",
    slug: "busan-haeundae",
    imageUrl: "/images/haeundae.jpg",
    description: "바다가 보이는 카페에서 일하는 로망",
    overallRating: 4.5,
    cafeRating: 4.5,
    costRating: 3.8,
    internetRating: 5.0,
    housingRating: 4.0,
    reviewCount: 412,
    likeCount: 1023,
    monthlyCost: 1550000,
    rentCost: 500000,
    cafeCost: 4000,
    currentTemp: 15,
    currentWeather: "구름조금",
    currentAQI: 28,
    tags: ["바다", "온천", "관광"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: "4",
    name: "강릉",
    region: "강원",
    slug: "gangneung",
    imageUrl: "/images/gangneung.jpg",
    description: "커피의 도시, 바다와 산이 공존하는 곳",
    overallRating: 4.4,
    cafeRating: 4.9,
    costRating: 4.5,
    internetRating: 4.3,
    housingRating: 4.2,
    reviewCount: 156,
    likeCount: 423,
    monthlyCost: 1350000,
    rentCost: 450000,
    cafeCost: 4000,
    currentTemp: 10,
    currentWeather: "맑음",
    currentAQI: 18,
    tags: ["커피", "바다", "조용함"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "5",
    name: "전주",
    region: "전라",
    slug: "jeonju",
    imageUrl: "/images/jeonju.jpg",
    description: "한옥마을과 맛집이 있는 문화도시",
    overallRating: 4.2,
    cafeRating: 4.3,
    costRating: 4.7,
    internetRating: 4.5,
    housingRating: 4.5,
    reviewCount: 134,
    likeCount: 312,
    monthlyCost: 1200000,
    rentCost: 400000,
    cafeCost: 3500,
    currentTemp: 13,
    currentWeather: "흐림",
    currentAQI: 35,
    tags: ["문화", "맛집", "저렴"],
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-10-30"),
  },
];

// Mock Meetups Data
export const mockMeetups: Meetup[] = [
  {
    id: "1",
    cityId: "1",
    cityName: "서울 성수동",
    hostId: "host1",
    title: "성수동 노마드들과 저녁 식사!",
    description: "성수동에서 일하는 디지털 노마드들과 함께 저녁 식사를 하며 네트워킹해요",
    location: "대림창고 카페",
    address: "서울시 성동구 연무장길 74",
    dateTime: new Date("2024-11-15T19:00:00"),
    status: "confirmed",
    rsvpCount: 12,
    rsvpUsers: ["user1", "user2", "user3", "user4", "user5"],
    rsvpUserImages: ["/images/user1.jpg", "/images/user2.jpg", "/images/user3.jpg"],
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "2",
    cityId: "2",
    cityName: "제주 제주시",
    hostId: "host2",
    title: "주말 브런치 & 네트워킹",
    description: "제주에서 활동하는 노마드들과 함께하는 브런치 모임",
    location: "모닝커피 제주",
    address: "제주시 첨단로 213-65",
    dateTime: new Date("2024-11-16T10:00:00"),
    status: "confirmed",
    rsvpCount: 8,
    rsvpUsers: ["user6", "user7", "user8"],
    rsvpUserImages: ["/images/user4.jpg", "/images/user5.jpg", "/images/user6.jpg"],
    createdAt: new Date("2024-11-02"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: "3",
    cityId: "3",
    cityName: "부산 해운대",
    hostId: "host3",
    title: "해운대 코워킹 투어",
    description: "해운대의 숨은 코워킹 카페들을 함께 돌아보는 모임",
    location: "더베이101 카페",
    address: "부산시 해운대구 동백로 52",
    dateTime: new Date("2024-11-20T14:00:00"),
    status: "confirmed",
    rsvpCount: 15,
    rsvpUsers: ["user9", "user10", "user11", "user12"],
    rsvpUserImages: ["/images/user7.jpg", "/images/user8.jpg", "/images/user9.jpg"],
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: "4",
    cityId: "4",
    cityName: "강릉",
    hostId: "host4",
    title: "강릉 커피 투어",
    description: "커피의 도시 강릉에서 유명 카페들을 함께 방문해요",
    location: "테라로사 커피공장",
    address: "강릉시 구정면 현천길 7",
    dateTime: new Date("2024-11-18T11:00:00"),
    status: "pending",
    rsvpCount: 2,
    rsvpUsers: ["user13", "user14"],
    rsvpUserImages: ["/images/user10.jpg", "/images/user11.jpg"],
    createdAt: new Date("2024-11-03"),
    updatedAt: new Date("2024-11-03"),
  },
];

// Mock Reviews Data
export const mockReviews: Review[] = [
  {
    id: "1",
    cityId: "1",
    userId: "user1",
    userName: "김디지털",
    cityName: "서울 성수동",
    rating: 5.0,
    content: "카페가 정말 많고 분위기도 좋아요. 콘센트 걱정 없고 와이파이도 빠릅니다.",
    tags: ["카페천국", "콘센트많음", "와이파이빠름"],
    createdAt: new Date("2024-11-03T14:30:00"),
    updatedAt: new Date("2024-11-03T14:30:00"),
  },
  {
    id: "2",
    cityId: "2",
    userId: "user2",
    userName: "박노마드",
    cityName: "제주 제주시",
    rating: 4.5,
    content: "자연이 아름답고 여유로운 분위기가 좋아요. 다만 생활비가 생각보다 높네요.",
    tags: ["자연", "힐링", "조용함"],
    createdAt: new Date("2024-11-03T10:15:00"),
    updatedAt: new Date("2024-11-03T10:15:00"),
  },
  {
    id: "3",
    cityId: "3",
    userId: "user3",
    userName: "이프리랜서",
    cityName: "부산 해운대",
    rating: 4.8,
    content: "바다 보면서 일할 수 있는 카페들이 많아요. 날씨도 좋고 사람들도 친절합니다!",
    tags: ["바다뷰", "날씨좋음", "친절"],
    createdAt: new Date("2024-11-02T16:45:00"),
    updatedAt: new Date("2024-11-02T16:45:00"),
  },
];
